package model.views;

import model.entity.XX_OM_POC_H_TEOImpl;

import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Dec 03 10:03:52 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XX_OM_POC_H_TVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        PocId {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getPocId();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setPocId((Number)value);
            }
        }
        ,
        BuyerName {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getBuyerName();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setBuyerName((String)value);
            }
        }
        ,
        SeasonName {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getSeasonName();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setSeasonName((String)value);
            }
        }
        ,
        StyleName {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getStyleName();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setStyleName((String)value);
            }
        }
        ,
        BrandName {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getBrandName();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setBrandName((String)value);
            }
        }
        ,
        FitName {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getFitName();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setFitName((String)value);
            }
        }
        ,
        OrderQantity {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getOrderQantity();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setOrderQantity((Number)value);
            }
        }
        ,
        LcUnit {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getLcUnit();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setLcUnit((Number)value);
            }
        }
        ,
        BuyerId {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getBuyerId();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setBuyerId((Number)value);
            }
        }
        ,
        Season {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        Style {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getStyle();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        StyleDescription {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getStyleDescription();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setStyleDescription((String)value);
            }
        }
        ,
        Brand {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getBrand();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setBrand((String)value);
            }
        }
        ,
        Fit {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getFit();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setFit((String)value);
            }
        }
        ,
        EndUser {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getEndUser();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setEndUser((String)value);
            }
        }
        ,
        ItemDescription {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getItemDescription();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setItemDescription((String)value);
            }
        }
        ,
        OrderQty {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getOrderQty();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setOrderQty((Number)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        GmApproval {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getGmApproval();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setGmApproval((String)value);
            }
        }
        ,
        VersionNo {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getVersionNo();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setVersionNo((Number)value);
            }
        }
        ,
        VersionDate {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getVersionDate();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setVersionDate((Date)value);
            }
        }
        ,
        RespId {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getRespId();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setRespId((Number)value);
            }
        }
        ,
        TrackingBasis {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getTrackingBasis();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setTrackingBasis((String)value);
            }
        }
        ,
        ItemPurchaseType {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getItemPurchaseType();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setItemPurchaseType((String)value);
            }
        }
        ,
        Status {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getStatus();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setStatus((Number)value);
            }
        }
        ,
        FabricFinance {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getFabricFinance();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setFabricFinance((Number)value);
            }
        }
        ,
        TrimFinance {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getTrimFinance();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setTrimFinance((Number)value);
            }
        }
        ,
        WashFinance {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getWashFinance();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setWashFinance((Number)value);
            }
        }
        ,
        AlternetSeason {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getAlternetSeason();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAlternetSeason((String)value);
            }
        }
        ,
        Dept {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getDept();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setDept((Number)value);
            }
        }
        ,
        CmMerchandiserD {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getCmMerchandiserD();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setCmMerchandiserD((String)value);
            }
        }
        ,
        Buyer {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getBuyer();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setBuyer((String)value);
            }
        }
        ,
        CreatedByName {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getCreatedByName();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setCreatedByName((String)value);
            }
        }
        ,
        GmStatus {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getGmStatus();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setGmStatus((String)value);
            }
        }
        ,
        OrgName {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getOrgName();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setOrgName((String)value);
            }
        }
        ,
        OrderQtyAll {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getOrderQtyAll();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setOrderQtyAll((Number)value);
            }
        }
        ,
        XX_OM_POC_L_TVO {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getXX_OM_POC_L_TVO();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Buyerlov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getBuyerlov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        Seasonlov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getSeasonlov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        branchlove1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getbranchlove1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemPurchaseTypeLov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getItemPurchaseTypeLov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        FitLov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getFitLov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        EndUserLov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getEndUserLov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ItemDecLov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getItemDecLov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        LcUnitLov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getLcUnitLov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        flux_StatusLov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getflux_StatusLov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        chgseasonlov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getchgseasonlov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        chgbrandlov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getchgbrandlov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        BuyerUMLov1 {
            public Object get(XX_OM_POC_H_TVORowImpl obj) {
                return obj.getBuyerUMLov1();
            }

            public void put(XX_OM_POC_H_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(XX_OM_POC_H_TVORowImpl object);

        public abstract void put(XX_OM_POC_H_TVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int POCID = AttributesEnum.PocId.index();
    public static final int BUYERNAME = AttributesEnum.BuyerName.index();
    public static final int SEASONNAME = AttributesEnum.SeasonName.index();
    public static final int STYLENAME = AttributesEnum.StyleName.index();
    public static final int BRANDNAME = AttributesEnum.BrandName.index();
    public static final int FITNAME = AttributesEnum.FitName.index();
    public static final int ORDERQANTITY = AttributesEnum.OrderQantity.index();
    public static final int LCUNIT = AttributesEnum.LcUnit.index();
    public static final int BUYERID = AttributesEnum.BuyerId.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int STYLEDESCRIPTION = AttributesEnum.StyleDescription.index();
    public static final int BRAND = AttributesEnum.Brand.index();
    public static final int FIT = AttributesEnum.Fit.index();
    public static final int ENDUSER = AttributesEnum.EndUser.index();
    public static final int ITEMDESCRIPTION = AttributesEnum.ItemDescription.index();
    public static final int ORDERQTY = AttributesEnum.OrderQty.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int GMAPPROVAL = AttributesEnum.GmApproval.index();
    public static final int VERSIONNO = AttributesEnum.VersionNo.index();
    public static final int VERSIONDATE = AttributesEnum.VersionDate.index();
    public static final int RESPID = AttributesEnum.RespId.index();
    public static final int TRACKINGBASIS = AttributesEnum.TrackingBasis.index();
    public static final int ITEMPURCHASETYPE = AttributesEnum.ItemPurchaseType.index();
    public static final int STATUS = AttributesEnum.Status.index();
    public static final int FABRICFINANCE = AttributesEnum.FabricFinance.index();
    public static final int TRIMFINANCE = AttributesEnum.TrimFinance.index();
    public static final int WASHFINANCE = AttributesEnum.WashFinance.index();
    public static final int ALTERNETSEASON = AttributesEnum.AlternetSeason.index();
    public static final int DEPT = AttributesEnum.Dept.index();
    public static final int CMMERCHANDISERD = AttributesEnum.CmMerchandiserD.index();
    public static final int BUYER = AttributesEnum.Buyer.index();
    public static final int CREATEDBYNAME = AttributesEnum.CreatedByName.index();
    public static final int GMSTATUS = AttributesEnum.GmStatus.index();
    public static final int ORGNAME = AttributesEnum.OrgName.index();
    public static final int ORDERQTYALL = AttributesEnum.OrderQtyAll.index();
    public static final int XX_OM_POC_L_TVO = AttributesEnum.XX_OM_POC_L_TVO.index();
    public static final int BUYERLOV1 = AttributesEnum.Buyerlov1.index();
    public static final int SEASONLOV1 = AttributesEnum.Seasonlov1.index();
    public static final int BRANCHLOVE1 = AttributesEnum.branchlove1.index();
    public static final int ITEMPURCHASETYPELOV1 = AttributesEnum.ItemPurchaseTypeLov1.index();
    public static final int FITLOV1 = AttributesEnum.FitLov1.index();
    public static final int ENDUSERLOV1 = AttributesEnum.EndUserLov1.index();
    public static final int ITEMDECLOV1 = AttributesEnum.ItemDecLov1.index();
    public static final int LCUNITLOV1 = AttributesEnum.LcUnitLov1.index();
    public static final int FLUX_STATUSLOV1 = AttributesEnum.flux_StatusLov1.index();
    public static final int CHGSEASONLOV1 = AttributesEnum.chgseasonlov1.index();
    public static final int CHGBRANDLOV1 = AttributesEnum.chgbrandlov1.index();
    public static final int BUYERUMLOV1 = AttributesEnum.BuyerUMLov1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XX_OM_POC_H_TVORowImpl() {
    }

    /**
     * Gets XX_OM_POC_H_TEO entity object.
     * @return the XX_OM_POC_H_TEO
     */
    public XX_OM_POC_H_TEOImpl getXX_OM_POC_H_TEO() {
        return (XX_OM_POC_H_TEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for POC_ID using the alias name PocId.
     * @return the POC_ID
     */
    public Number getPocId() {
        return (Number) getAttributeInternal(POCID);
    }

    /**
     * Sets <code>value</code> as attribute value for POC_ID using the alias name PocId.
     * @param value value to set the POC_ID
     */
    public void setPocId(Number value) {
        setAttributeInternal(POCID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BuyerName.
     * @return the BuyerName
     */
    public String getBuyerName() {
        return (String) getAttributeInternal(BUYERNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName.
     * @param value value to set the  BuyerName
     */
    public void setBuyerName(String value) {
        setAttributeInternal(BUYERNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SeasonName.
     * @return the SeasonName
     */
    public String getSeasonName() {
        return (String) getAttributeInternal(SEASONNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SeasonName.
     * @param value value to set the  SeasonName
     */
    public void setSeasonName(String value) {
        setAttributeInternal(SEASONNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute StyleName.
     * @return the StyleName
     */
    public String getStyleName() {
        return (String) getAttributeInternal(STYLENAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute StyleName.
     * @param value value to set the  StyleName
     */
    public void setStyleName(String value) {
        setAttributeInternal(STYLENAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute BrandName.
     * @return the BrandName
     */
    public String getBrandName() {
        return (String) getAttributeInternal(BRANDNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute BrandName.
     * @param value value to set the  BrandName
     */
    public void setBrandName(String value) {
        setAttributeInternal(BRANDNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FitName.
     * @return the FitName
     */
    public String getFitName() {
        return (String) getAttributeInternal(FITNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FitName.
     * @param value value to set the  FitName
     */
    public void setFitName(String value) {
        setAttributeInternal(FITNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderQantity.
     * @return the OrderQantity
     */
    public Number getOrderQantity() {
        return (Number) getAttributeInternal(ORDERQANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderQantity.
     * @param value value to set the  OrderQantity
     */
    public void setOrderQantity(Number value) {
        setAttributeInternal(ORDERQANTITY, value);
    }

    /**
     * Gets the attribute value for LC_UNIT using the alias name LcUnit.
     * @return the LC_UNIT
     */
    public Number getLcUnit() {
        return (Number) getAttributeInternal(LCUNIT);
    }

    /**
     * Sets <code>value</code> as attribute value for LC_UNIT using the alias name LcUnit.
     * @param value value to set the LC_UNIT
     */
    public void setLcUnit(Number value) {
        setAttributeInternal(LCUNIT, value);
    }

    /**
     * Gets the attribute value for BUYER_ID using the alias name BuyerId.
     * @return the BUYER_ID
     */
    public Number getBuyerId() {
        return (Number) getAttributeInternal(BUYERID);
    }

    /**
     * Sets <code>value</code> as attribute value for BUYER_ID using the alias name BuyerId.
     * @param value value to set the BUYER_ID
     */
    public void setBuyerId(Number value) {
        setAttributeInternal(BUYERID, value);
    }

    /**
     * Gets the attribute value for SEASON using the alias name Season.
     * @return the SEASON
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as attribute value for SEASON using the alias name Season.
     * @param value value to set the SEASON
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for STYLE using the alias name Style.
     * @return the STYLE
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE using the alias name Style.
     * @param value value to set the STYLE
     */
    public void setStyle(String value) {
        value=  value.trim();   // added on 11 mar 2021 by Arif to eliminate space before or after value
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for STYLE_DESCRIPTION using the alias name StyleDescription.
     * @return the STYLE_DESCRIPTION
     */
    public String getStyleDescription() {
        return (String) getAttributeInternal(STYLEDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_DESCRIPTION using the alias name StyleDescription.
     * @param value value to set the STYLE_DESCRIPTION
     */
    public void setStyleDescription(String value) {
        setAttributeInternal(STYLEDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for BRAND using the alias name Brand.
     * @return the BRAND
     */
    public String getBrand() {
        return (String) getAttributeInternal(BRAND);
    }

    /**
     * Sets <code>value</code> as attribute value for BRAND using the alias name Brand.
     * @param value value to set the BRAND
     */
    public void setBrand(String value) {
        setAttributeInternal(BRAND, value);
    }

    /**
     * Gets the attribute value for FIT using the alias name Fit.
     * @return the FIT
     */
    public String getFit() {
        return (String) getAttributeInternal(FIT);
    }

    /**
     * Sets <code>value</code> as attribute value for FIT using the alias name Fit.
     * @param value value to set the FIT
     */
    public void setFit(String value) {
        setAttributeInternal(FIT, value);
    }

    /**
     * Gets the attribute value for END_USER using the alias name EndUser.
     * @return the END_USER
     */
    public String getEndUser() {
        return (String) getAttributeInternal(ENDUSER);
    }

    /**
     * Sets <code>value</code> as attribute value for END_USER using the alias name EndUser.
     * @param value value to set the END_USER
     */
    public void setEndUser(String value) {
        setAttributeInternal(ENDUSER, value);
    }

    /**
     * Gets the attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @return the ITEM_DESCRIPTION
     */
    public String getItemDescription() {
        return (String) getAttributeInternal(ITEMDESCRIPTION);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_DESCRIPTION using the alias name ItemDescription.
     * @param value value to set the ITEM_DESCRIPTION
     */
    public void setItemDescription(String value) {
        setAttributeInternal(ITEMDESCRIPTION, value);
    }

    /**
     * Gets the attribute value for ORDER_QTY using the alias name OrderQty.
     * @return the ORDER_QTY
     */
    public Number getOrderQty() {
        return (Number) getAttributeInternal(ORDERQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for ORDER_QTY using the alias name OrderQty.
     * @param value value to set the ORDER_QTY
     */
    public void setOrderQty(Number value) {
        setAttributeInternal(ORDERQTY, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for GM_APPROVAL using the alias name GmApproval.
     * @return the GM_APPROVAL
     */
    public String getGmApproval() {
        return (String) getAttributeInternal(GMAPPROVAL);
    }

    /**
     * Sets <code>value</code> as attribute value for GM_APPROVAL using the alias name GmApproval.
     * @param value value to set the GM_APPROVAL
     */
    public void setGmApproval(String value) {
        setAttributeInternal(GMAPPROVAL, value);
    }

    /**
     * Gets the attribute value for VERSION_NO using the alias name VersionNo.
     * @return the VERSION_NO
     */
    public Number getVersionNo() {
        return (Number) getAttributeInternal(VERSIONNO);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_NO using the alias name VersionNo.
     * @param value value to set the VERSION_NO
     */
    public void setVersionNo(Number value) {
        setAttributeInternal(VERSIONNO, value);
    }

    /**
     * Gets the attribute value for VERSION_DATE using the alias name VersionDate.
     * @return the VERSION_DATE
     */
    public Date getVersionDate() {
        return (Date) getAttributeInternal(VERSIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for VERSION_DATE using the alias name VersionDate.
     * @param value value to set the VERSION_DATE
     */
    public void setVersionDate(Date value) {
        setAttributeInternal(VERSIONDATE, value);
    }

    /**
     * Gets the attribute value for RESP_ID using the alias name RespId.
     * @return the RESP_ID
     */
    public Number getRespId() {
        return (Number) getAttributeInternal(RESPID);
    }

    /**
     * Sets <code>value</code> as attribute value for RESP_ID using the alias name RespId.
     * @param value value to set the RESP_ID
     */
    public void setRespId(Number value) {
        setAttributeInternal(RESPID, value);
    }

    /**
     * Gets the attribute value for TRACKING_BASIS using the alias name TrackingBasis.
     * @return the TRACKING_BASIS
     */
    public String getTrackingBasis() {
        return (String) getAttributeInternal(TRACKINGBASIS);
    }

    /**
     * Sets <code>value</code> as attribute value for TRACKING_BASIS using the alias name TrackingBasis.
     * @param value value to set the TRACKING_BASIS
     */
    public void setTrackingBasis(String value) {
        setAttributeInternal(TRACKINGBASIS, value);
    }

    /**
     * Gets the attribute value for ITEM_PURCHASE_TYPE using the alias name ItemPurchaseType.
     * @return the ITEM_PURCHASE_TYPE
     */
    public String getItemPurchaseType() {
        return (String) getAttributeInternal(ITEMPURCHASETYPE);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_PURCHASE_TYPE using the alias name ItemPurchaseType.
     * @param value value to set the ITEM_PURCHASE_TYPE
     */
    public void setItemPurchaseType(String value) {
        setAttributeInternal(ITEMPURCHASETYPE, value);
    }

    /**
     * Gets the attribute value for STATUS using the alias name Status.
     * @return the STATUS
     */
    public Number getStatus() {
        return (Number) getAttributeInternal(STATUS);
    }

    /**
     * Sets <code>value</code> as attribute value for STATUS using the alias name Status.
     * @param value value to set the STATUS
     */
    public void setStatus(Number value) {
        setAttributeInternal(STATUS, value);
    }

    /**
     * Gets the attribute value for FABRIC_FINANCE using the alias name FabricFinance.
     * @return the FABRIC_FINANCE
     */
    public Number getFabricFinance() {
        return (Number) getAttributeInternal(FABRICFINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for FABRIC_FINANCE using the alias name FabricFinance.
     * @param value value to set the FABRIC_FINANCE
     */
    public void setFabricFinance(Number value) {
        setAttributeInternal(FABRICFINANCE, value);
    }

    /**
     * Gets the attribute value for TRIM_FINANCE using the alias name TrimFinance.
     * @return the TRIM_FINANCE
     */
    public Number getTrimFinance() {
        return (Number) getAttributeInternal(TRIMFINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for TRIM_FINANCE using the alias name TrimFinance.
     * @param value value to set the TRIM_FINANCE
     */
    public void setTrimFinance(Number value) {
        setAttributeInternal(TRIMFINANCE, value);
    }

    /**
     * Gets the attribute value for WASH_FINANCE using the alias name WashFinance.
     * @return the WASH_FINANCE
     */
    public Number getWashFinance() {
        return (Number) getAttributeInternal(WASHFINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_FINANCE using the alias name WashFinance.
     * @param value value to set the WASH_FINANCE
     */
    public void setWashFinance(Number value) {
        setAttributeInternal(WASHFINANCE, value);
    }

    /**
     * Gets the attribute value for ALTERNET_SEASON using the alias name AlternetSeason.
     * @return the ALTERNET_SEASON
     */
    public String getAlternetSeason() {
        return (String) getAttributeInternal(ALTERNETSEASON);
    }

    /**
     * Sets <code>value</code> as attribute value for ALTERNET_SEASON using the alias name AlternetSeason.
     * @param value value to set the ALTERNET_SEASON
     */
    public void setAlternetSeason(String value) {
        setAttributeInternal(ALTERNETSEASON, value);
    }

    /**
     * Gets the attribute value for DEPT using the alias name Dept.
     * @return the DEPT
     */
    public Number getDept() {
        return (Number) getAttributeInternal(DEPT);
    }

    /**
     * Sets <code>value</code> as attribute value for DEPT using the alias name Dept.
     * @param value value to set the DEPT
     */
    public void setDept(Number value) {
        setAttributeInternal(DEPT, value);
    }

    /**
     * Gets the attribute value for CM_MERCHANDISER_D using the alias name CmMerchandiserD.
     * @return the CM_MERCHANDISER_D
     */
    public String getCmMerchandiserD() {
        return (String) getAttributeInternal(CMMERCHANDISERD);
    }

    /**
     * Sets <code>value</code> as attribute value for CM_MERCHANDISER_D using the alias name CmMerchandiserD.
     * @param value value to set the CM_MERCHANDISER_D
     */
    public void setCmMerchandiserD(String value) {
        setAttributeInternal(CMMERCHANDISERD, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Buyer.
     * @return the Buyer
     */
    public String getBuyer() {
        return (String) getAttributeInternal(BUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Buyer.
     * @param value value to set the  Buyer
     */
    public void setBuyer(String value) {
        setAttributeInternal(BUYER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CreatedByName.
     * @return the CreatedByName
     */
    public String getCreatedByName() {
        return (String) getAttributeInternal(CREATEDBYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CreatedByName.
     * @param value value to set the  CreatedByName
     */
    public void setCreatedByName(String value) {
        setAttributeInternal(CREATEDBYNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute GmStatus.
     * @return the GmStatus
     */
    public String getGmStatus() {
        return (String) getAttributeInternal(GMSTATUS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute GmStatus.
     * @param value value to set the  GmStatus
     */
    public void setGmStatus(String value) {
        setAttributeInternal(GMSTATUS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrgName.
     * @return the OrgName
     */
    public String getOrgName() {
        return (String) getAttributeInternal(ORGNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrgName.
     * @param value value to set the  OrgName
     */
    public void setOrgName(String value) {
        setAttributeInternal(ORGNAME, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OrderQtyAll.
     * @return the OrderQtyAll
     */
    public Number getOrderQtyAll() {
        return (Number) getAttributeInternal(ORDERQTYALL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OrderQtyAll.
     * @param value value to set the  OrderQtyAll
     */
    public void setOrderQtyAll(Number value) {
        setAttributeInternal(ORDERQTYALL, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XX_OM_POC_L_TVO.
     */
    public RowIterator getXX_OM_POC_L_TVO() {
        return (RowIterator)getAttributeInternal(XX_OM_POC_L_TVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Buyerlov1.
     */
    public RowSet getBuyerlov1() {
        return (RowSet)getAttributeInternal(BUYERLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> Seasonlov1.
     */
    public RowSet getSeasonlov1() {
        return (RowSet)getAttributeInternal(SEASONLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> branchlove1.
     */
    public RowSet getbranchlove1() {
        return (RowSet)getAttributeInternal(BRANCHLOVE1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemPurchaseTypeLov1.
     */
    public RowSet getItemPurchaseTypeLov1() {
        return (RowSet)getAttributeInternal(ITEMPURCHASETYPELOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> FitLov1.
     */
    public RowSet getFitLov1() {
        return (RowSet)getAttributeInternal(FITLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> EndUserLov1.
     */
    public RowSet getEndUserLov1() {
        return (RowSet)getAttributeInternal(ENDUSERLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ItemDecLov1.
     */
    public RowSet getItemDecLov1() {
        return (RowSet)getAttributeInternal(ITEMDECLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> LcUnitLov1.
     */
    public RowSet getLcUnitLov1() {
        return (RowSet)getAttributeInternal(LCUNITLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> flux_StatusLov1.
     */
    public RowSet getflux_StatusLov1() {
        return (RowSet)getAttributeInternal(FLUX_STATUSLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> chgseasonlov1.
     */
    public RowSet getchgseasonlov1() {
        return (RowSet)getAttributeInternal(CHGSEASONLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> chgbrandlov1.
     */
    public RowSet getchgbrandlov1() {
        return (RowSet)getAttributeInternal(CHGBRANDLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> BuyerUMLov1.
     */
    public RowSet getBuyerUMLov1() {
        return (RowSet)getAttributeInternal(BUYERUMLOV1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
