package model.views;

import model.entity.XX_OM_POC_L_TEOImpl;

import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Mar 11 10:33:09 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XX_OM_POC_L_TVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        FabricDetails {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFabricDetails();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFabricDetails((String)value);
            }
        }
        ,
        Wash {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getWash();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setWash((String)value);
            }
        }
        ,
        Colour {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getColour();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setColour((String)value);
            }
        }
        ,
        FabricCostWithFinance {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFabricCostWithFinance();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFabricCostWithFinance((Number)value);
            }
        }
        ,
        TrimCostt {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getTrimCostt();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setTrimCostt((Number)value);
            }
        }
        ,
        WashCostt {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getWashCostt();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setWashCostt((Number)value);
            }
        }
        ,
        OthersCost {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getOthersCost();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setOthersCost((Number)value);
            }
        }
        ,
        CmValue {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getCmValue();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setCmValue((Number)value);
            }
        }
        ,
        FobValue {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFobValue();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFobValue((Number)value);
            }
        }
        ,
        RemarksDetails {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getRemarksDetails();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setRemarksDetails((String)value);
            }
        }
        ,
        FobId {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFobId();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFobId((Number)value);
            }
        }
        ,
        PocId {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getPocId();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setPocId((Number)value);
            }
        }
        ,
        SystemId {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getSystemId();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setSystemId((Number)value);
            }
        }
        ,
        WashName {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getWashName();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setWashName((String)value);
            }
        }
        ,
        Color {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getColor();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setColor((String)value);
            }
        }
        ,
        FobWitoutComm {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFobWitoutComm();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFobWitoutComm((Number)value);
            }
        }
        ,
        FobWithComm {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFobWithComm();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFobWithComm((Number)value);
            }
        }
        ,
        FobWithSmsSample {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFobWithSmsSample();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFobWithSmsSample((Number)value);
            }
        }
        ,
        Cost {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getCost();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setCost((Number)value);
            }
        }
        ,
        Finance {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFinance();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFinance((Number)value);
            }
        }
        ,
        Profit {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getProfit();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setProfit((Number)value);
            }
        }
        ,
        ItemId {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getItemId();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setItemId((Number)value);
            }
        }
        ,
        CommisonPrcnt {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getCommisonPrcnt();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setCommisonPrcnt((Number)value);
            }
        }
        ,
        Fob {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFob();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFob((Number)value);
            }
        }
        ,
        FabricCost {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFabricCost();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFabricCost((Number)value);
            }
        }
        ,
        TrimCost {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getTrimCost();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setTrimCost((Number)value);
            }
        }
        ,
        WashCost {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getWashCost();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setWashCost((Number)value);
            }
        }
        ,
        CmMerchand {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getCmMerchand();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setCmMerchand((Number)value);
            }
        }
        ,
        Smv {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getSmv();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setSmv((Number)value);
            }
        }
        ,
        FactoryAvgEf {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFactoryAvgEf();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFactoryAvgEf((Number)value);
            }
        }
        ,
        ProdCostLinePerH {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getProdCostLinePerH();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setProdCostLinePerH((Number)value);
            }
        }
        ,
        CmManagement {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getCmManagement();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setCmManagement((Number)value);
            }
        }
        ,
        Remarks {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getRemarks();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setRemarks((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setCreatedBy((Number)value);
            }
        }
        ,
        CreationDate {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getCreationDate();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setCreationDate((Date)value);
            }
        }
        ,
        LastUpdatedBy {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getLastUpdatedBy();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setLastUpdatedBy((Number)value);
            }
        }
        ,
        LastUpdatedDate {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getLastUpdatedDate();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setLastUpdatedDate((Date)value);
            }
        }
        ,
        FabricDesc {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getFabricDesc();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setFabricDesc((String)value);
            }
        }
        ,
        Cm {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getCm();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setCm((Number)value);
            }
        }
        ,
        Others {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getOthers();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setOthers((Number)value);
            }
        }
        ,
        SmsQty {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getSmsQty();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setSmsQty((Number)value);
            }
        }
        ,
        Sam {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getSam();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setSam((Number)value);
            }
        }
        ,
        CostNew {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getCostNew();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setCostNew((Number)value);
            }
        }
        ,
        TotalCost {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getTotalCost();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setTotalCost((Number)value);
            }
        }
        ,
        StyleEfficiency {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getStyleEfficiency();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setStyleEfficiency((Number)value);
            }
        }
        ,
        OtherCharge {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getOtherCharge();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setOtherCharge((Number)value);
            }
        }
        ,
        Shipment {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getShipment();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setShipment((String)value);
            }
        }
        ,
        ShipmentValue {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getShipmentValue();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setShipmentValue((Number)value);
            }
        }
        ,
        ProdPerLinePerH {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getProdPerLinePerH();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setProdPerLinePerH((Number)value);
            }
        }
        ,
        ItemTotal {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getItemTotal();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setItemTotal((Number)value);
            }
        }
        ,
        WetTotal {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getWetTotal();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setWetTotal((Number)value);
            }
        }
        ,
        DryTotal {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getDryTotal();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setDryTotal((Number)value);
            }
        }
        ,
        trims_total {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.gettrims_total();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.settrims_total((String)value);
            }
        }
        ,
        others_total {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getothers_total();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setothers_total((String)value);
            }
        }
        ,
        fab_total {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getfab_total();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setfab_total((String)value);
            }
        }
        ,
        D2_TVO1_Total {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getD2_TVO1_Total();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setD2_TVO1_Total((String)value);
            }
        }
        ,
        D2_TVO_total {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getD2_TVO_total();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setD2_TVO_total((String)value);
            }
        }
        ,
        XX_OM_POC_H_TVO {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getXX_OM_POC_H_TVO();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XX_OM_POC_D1_TVO {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getXX_OM_POC_D1_TVO();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XX_OM_POC_D2_TVO {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getXX_OM_POC_D2_TVO();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        XX_OM_POC_D2_TVO2 {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getXX_OM_POC_D2_TVO2();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        trimsVO {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.gettrimsVO();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        others_VO {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getothers_VO();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        ASAM_AStyleEffiVO {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getASAM_AStyleEffiVO();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        short_or_eccess_VO {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getshort_or_eccess_VO();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        MDSIRsVO {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getMDSIRsVO();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        colorLov1 {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getcolorLov1();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ,
        shorExcessVo1 {
            public Object get(XX_OM_POC_L_TVORowImpl obj) {
                return obj.getshorExcessVo1();
            }

            public void put(XX_OM_POC_L_TVORowImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(XX_OM_POC_L_TVORowImpl object);

        public abstract void put(XX_OM_POC_L_TVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int FABRICDETAILS = AttributesEnum.FabricDetails.index();
    public static final int WASH = AttributesEnum.Wash.index();
    public static final int COLOUR = AttributesEnum.Colour.index();
    public static final int FABRICCOSTWITHFINANCE = AttributesEnum.FabricCostWithFinance.index();
    public static final int TRIMCOSTT = AttributesEnum.TrimCostt.index();
    public static final int WASHCOSTT = AttributesEnum.WashCostt.index();
    public static final int OTHERSCOST = AttributesEnum.OthersCost.index();
    public static final int CMVALUE = AttributesEnum.CmValue.index();
    public static final int FOBVALUE = AttributesEnum.FobValue.index();
    public static final int REMARKSDETAILS = AttributesEnum.RemarksDetails.index();
    public static final int FOBID = AttributesEnum.FobId.index();
    public static final int POCID = AttributesEnum.PocId.index();
    public static final int SYSTEMID = AttributesEnum.SystemId.index();
    public static final int WASHNAME = AttributesEnum.WashName.index();
    public static final int COLOR = AttributesEnum.Color.index();
    public static final int FOBWITOUTCOMM = AttributesEnum.FobWitoutComm.index();
    public static final int FOBWITHCOMM = AttributesEnum.FobWithComm.index();
    public static final int FOBWITHSMSSAMPLE = AttributesEnum.FobWithSmsSample.index();
    public static final int COST = AttributesEnum.Cost.index();
    public static final int FINANCE = AttributesEnum.Finance.index();
    public static final int PROFIT = AttributesEnum.Profit.index();
    public static final int ITEMID = AttributesEnum.ItemId.index();
    public static final int COMMISONPRCNT = AttributesEnum.CommisonPrcnt.index();
    public static final int FOB = AttributesEnum.Fob.index();
    public static final int FABRICCOST = AttributesEnum.FabricCost.index();
    public static final int TRIMCOST = AttributesEnum.TrimCost.index();
    public static final int WASHCOST = AttributesEnum.WashCost.index();
    public static final int CMMERCHAND = AttributesEnum.CmMerchand.index();
    public static final int SMV = AttributesEnum.Smv.index();
    public static final int FACTORYAVGEF = AttributesEnum.FactoryAvgEf.index();
    public static final int PRODCOSTLINEPERH = AttributesEnum.ProdCostLinePerH.index();
    public static final int CMMANAGEMENT = AttributesEnum.CmManagement.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int CREATIONDATE = AttributesEnum.CreationDate.index();
    public static final int LASTUPDATEDBY = AttributesEnum.LastUpdatedBy.index();
    public static final int LASTUPDATEDDATE = AttributesEnum.LastUpdatedDate.index();
    public static final int FABRICDESC = AttributesEnum.FabricDesc.index();
    public static final int CM = AttributesEnum.Cm.index();
    public static final int OTHERS = AttributesEnum.Others.index();
    public static final int SMSQTY = AttributesEnum.SmsQty.index();
    public static final int SAM = AttributesEnum.Sam.index();
    public static final int COSTNEW = AttributesEnum.CostNew.index();
    public static final int TOTALCOST = AttributesEnum.TotalCost.index();
    public static final int STYLEEFFICIENCY = AttributesEnum.StyleEfficiency.index();
    public static final int OTHERCHARGE = AttributesEnum.OtherCharge.index();
    public static final int SHIPMENT = AttributesEnum.Shipment.index();
    public static final int SHIPMENTVALUE = AttributesEnum.ShipmentValue.index();
    public static final int PRODPERLINEPERH = AttributesEnum.ProdPerLinePerH.index();
    public static final int ITEMTOTAL = AttributesEnum.ItemTotal.index();
    public static final int WETTOTAL = AttributesEnum.WetTotal.index();
    public static final int DRYTOTAL = AttributesEnum.DryTotal.index();
    public static final int TRIMS_TOTAL = AttributesEnum.trims_total.index();
    public static final int OTHERS_TOTAL = AttributesEnum.others_total.index();
    public static final int FAB_TOTAL = AttributesEnum.fab_total.index();
    public static final int D2_TVO1_TOTAL = AttributesEnum.D2_TVO1_Total.index();
    public static final int D2_TVO_TOTAL = AttributesEnum.D2_TVO_total.index();
    public static final int XX_OM_POC_H_TVO = AttributesEnum.XX_OM_POC_H_TVO.index();
    public static final int XX_OM_POC_D1_TVO = AttributesEnum.XX_OM_POC_D1_TVO.index();
    public static final int XX_OM_POC_D2_TVO = AttributesEnum.XX_OM_POC_D2_TVO.index();
    public static final int XX_OM_POC_D2_TVO2 = AttributesEnum.XX_OM_POC_D2_TVO2.index();
    public static final int TRIMSVO = AttributesEnum.trimsVO.index();
    public static final int OTHERS_VO = AttributesEnum.others_VO.index();
    public static final int ASAM_ASTYLEEFFIVO = AttributesEnum.ASAM_AStyleEffiVO.index();
    public static final int SHORT_OR_ECCESS_VO = AttributesEnum.short_or_eccess_VO.index();
    public static final int MDSIRSVO = AttributesEnum.MDSIRsVO.index();
    public static final int COLORLOV1 = AttributesEnum.colorLov1.index();
    public static final int SHOREXCESSVO1 = AttributesEnum.shorExcessVo1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public XX_OM_POC_L_TVORowImpl() {
    }

    /**
     * Gets XX_OM_POC_L_TEO entity object.
     * @return the XX_OM_POC_L_TEO
     */
    public XX_OM_POC_L_TEOImpl getXX_OM_POC_L_TEO() {
        return (XX_OM_POC_L_TEOImpl)getEntity(0);
    }

    /**
     * Gets the attribute value for the calculated attribute FabricDetails.
     * @return the FabricDetails
     */
    public String getFabricDetails() {
        return (String) getAttributeInternal(FABRICDETAILS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FabricDetails.
     * @param value value to set the  FabricDetails
     */
    public void setFabricDetails(String value) {
        setAttributeInternal(FABRICDETAILS, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Wash.
     * @return the Wash
     */
    public String getWash() {
        return (String) getAttributeInternal(WASH);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Wash.
     * @param value value to set the  Wash
     */
    public void setWash(String value) {
        setAttributeInternal(WASH, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Colour.
     * @return the Colour
     */
    public String getColour() {
        return (String) getAttributeInternal(COLOUR);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Colour.
     * @param value value to set the  Colour
     */
    public void setColour(String value) {
        setAttributeInternal(COLOUR, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FabricCostWithFinance.
     * @return the FabricCostWithFinance
     */
    public Number getFabricCostWithFinance() {
        return (Number) getAttributeInternal(FABRICCOSTWITHFINANCE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FabricCostWithFinance.
     * @param value value to set the  FabricCostWithFinance
     */
    public void setFabricCostWithFinance(Number value) {
        setAttributeInternal(FABRICCOSTWITHFINANCE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute TrimCostt.
     * @return the TrimCostt
     */
    public Number getTrimCostt() {
        return (Number) getAttributeInternal(TRIMCOSTT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute TrimCostt.
     * @param value value to set the  TrimCostt
     */
    public void setTrimCostt(Number value) {
        setAttributeInternal(TRIMCOSTT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WashCostt.
     * @return the WashCostt
     */
    public Number getWashCostt() {
        return (Number) getAttributeInternal(WASHCOSTT);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WashCostt.
     * @param value value to set the  WashCostt
     */
    public void setWashCostt(Number value) {
        setAttributeInternal(WASHCOSTT, value);
    }

    /**
     * Gets the attribute value for the calculated attribute OthersCost.
     * @return the OthersCost
     */
    public Number getOthersCost() {
        return (Number) getAttributeInternal(OTHERSCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute OthersCost.
     * @param value value to set the  OthersCost
     */
    public void setOthersCost(Number value) {
        setAttributeInternal(OTHERSCOST, value);
    }

    /**
     * Gets the attribute value for the calculated attribute CmValue.
     * @return the CmValue
     */
    public Number getCmValue() {
        return (Number) getAttributeInternal(CMVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute CmValue.
     * @param value value to set the  CmValue
     */
    public void setCmValue(Number value) {
        setAttributeInternal(CMVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute FobValue.
     * @return the FobValue
     */
    public Number getFobValue() {
        return (Number) getAttributeInternal(FOBVALUE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute FobValue.
     * @param value value to set the  FobValue
     */
    public void setFobValue(Number value) {
        setAttributeInternal(FOBVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute RemarksDetails.
     * @return the RemarksDetails
     */
    public String getRemarksDetails() {
        return (String) getAttributeInternal(REMARKSDETAILS);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute RemarksDetails.
     * @param value value to set the  RemarksDetails
     */
    public void setRemarksDetails(String value) {
        setAttributeInternal(REMARKSDETAILS, value);
    }

    /**
     * Gets the attribute value for FOB_ID using the alias name FobId.
     * @return the FOB_ID
     */
    public Number getFobId() {
        return (Number) getAttributeInternal(FOBID);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB_ID using the alias name FobId.
     * @param value value to set the FOB_ID
     */
    public void setFobId(Number value) {
        setAttributeInternal(FOBID, value);
    }

    /**
     * Gets the attribute value for POC_ID using the alias name PocId.
     * @return the POC_ID
     */
    public Number getPocId() {
        return (Number) getAttributeInternal(POCID);
    }

    /**
     * Sets <code>value</code> as attribute value for POC_ID using the alias name PocId.
     * @param value value to set the POC_ID
     */
    public void setPocId(Number value) {
        setAttributeInternal(POCID, value);
    }

    /**
     * Gets the attribute value for SYSTEM_ID using the alias name SystemId.
     * @return the SYSTEM_ID
     */
    public Number getSystemId() {
        return (Number) getAttributeInternal(SYSTEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for SYSTEM_ID using the alias name SystemId.
     * @param value value to set the SYSTEM_ID
     */
    public void setSystemId(Number value) {
        setAttributeInternal(SYSTEMID, value);
    }

    /**
     * Gets the attribute value for WASH_NAME using the alias name WashName.
     * @return the WASH_NAME
     */
    public String getWashName() {
        return (String) getAttributeInternal(WASHNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_NAME using the alias name WashName.
     * @param value value to set the WASH_NAME
     */
    public void setWashName(String value) {
        value=  value.trim();   // added on 11mar 2021 by arif  to eliminate space before or after value
        setAttributeInternal(WASHNAME, value);
    }

    /**
     * Gets the attribute value for COLOR using the alias name Color.
     * @return the COLOR
     */
    public String getColor() {
        return (String) getAttributeInternal(COLOR);
    }

    /**
     * Sets <code>value</code> as attribute value for COLOR using the alias name Color.
     * @param value value to set the COLOR
     */
    public void setColor(String value) {
        setAttributeInternal(COLOR, value);
    }

    /**
     * Gets the attribute value for FOB_WITOUT_COMM using the alias name FobWitoutComm.
     * @return the FOB_WITOUT_COMM
     */
    public Number getFobWitoutComm() {
        return (Number) getAttributeInternal(FOBWITOUTCOMM);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB_WITOUT_COMM using the alias name FobWitoutComm.
     * @param value value to set the FOB_WITOUT_COMM
     */
    public void setFobWitoutComm(Number value) {
        setAttributeInternal(FOBWITOUTCOMM, value);
    }

    /**
     * Gets the attribute value for FOB_WITH_COMM using the alias name FobWithComm.
     * @return the FOB_WITH_COMM
     */
    public Number getFobWithComm() {
        return (Number) getAttributeInternal(FOBWITHCOMM);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB_WITH_COMM using the alias name FobWithComm.
     * @param value value to set the FOB_WITH_COMM
     */
    public void setFobWithComm(Number value) {
        setAttributeInternal(FOBWITHCOMM, value);
    }

    /**
     * Gets the attribute value for FOB_WITH_SMS_SAMPLE using the alias name FobWithSmsSample.
     * @return the FOB_WITH_SMS_SAMPLE
     */
    public Number getFobWithSmsSample() {
        return (Number) getAttributeInternal(FOBWITHSMSSAMPLE);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB_WITH_SMS_SAMPLE using the alias name FobWithSmsSample.
     * @param value value to set the FOB_WITH_SMS_SAMPLE
     */
    public void setFobWithSmsSample(Number value) {
        setAttributeInternal(FOBWITHSMSSAMPLE, value);
    }

    /**
     * Gets the attribute value for COST using the alias name Cost.
     * @return the COST
     */
    public Number getCost() {
        return (Number) getAttributeInternal(COST);
    }

    /**
     * Sets <code>value</code> as attribute value for COST using the alias name Cost.
     * @param value value to set the COST
     */
    public void setCost(Number value) {
        setAttributeInternal(COST, value);
    }

    /**
     * Gets the attribute value for FINANCE using the alias name Finance.
     * @return the FINANCE
     */
    public Number getFinance() {
        return (Number) getAttributeInternal(FINANCE);
    }

    /**
     * Sets <code>value</code> as attribute value for FINANCE using the alias name Finance.
     * @param value value to set the FINANCE
     */
    public void setFinance(Number value) {
        setAttributeInternal(FINANCE, value);
    }

    /**
     * Gets the attribute value for PROFIT using the alias name Profit.
     * @return the PROFIT
     */
    public Number getProfit() {
        return (Number) getAttributeInternal(PROFIT);
    }

    /**
     * Sets <code>value</code> as attribute value for PROFIT using the alias name Profit.
     * @param value value to set the PROFIT
     */
    public void setProfit(Number value) {
        setAttributeInternal(PROFIT, value);
    }

    /**
     * Gets the attribute value for ITEM_ID using the alias name ItemId.
     * @return the ITEM_ID
     */
    public Number getItemId() {
        return (Number) getAttributeInternal(ITEMID);
    }

    /**
     * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId.
     * @param value value to set the ITEM_ID
     */
    public void setItemId(Number value) {
        setAttributeInternal(ITEMID, value);
    }

    /**
     * Gets the attribute value for COMMISON_PRCNT using the alias name CommisonPrcnt.
     * @return the COMMISON_PRCNT
     */
    public Number getCommisonPrcnt() {
        return (Number) getAttributeInternal(COMMISONPRCNT);
    }

    /**
     * Sets <code>value</code> as attribute value for COMMISON_PRCNT using the alias name CommisonPrcnt.
     * @param value value to set the COMMISON_PRCNT
     */
    public void setCommisonPrcnt(Number value) {
        setAttributeInternal(COMMISONPRCNT, value);
    }

    /**
     * Gets the attribute value for FOB using the alias name Fob.
     * @return the FOB
     */
    public Number getFob() {
        return (Number) getAttributeInternal(FOB);
    }

    /**
     * Sets <code>value</code> as attribute value for FOB using the alias name Fob.
     * @param value value to set the FOB
     */
    public void setFob(Number value) {
        setAttributeInternal(FOB, value);
    }

    /**
     * Gets the attribute value for FABRIC_COST using the alias name FabricCost.
     * @return the FABRIC_COST
     */
    public Number getFabricCost() {
        return (Number) getAttributeInternal(FABRICCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for FABRIC_COST using the alias name FabricCost.
     * @param value value to set the FABRIC_COST
     */
    public void setFabricCost(Number value) {
        setAttributeInternal(FABRICCOST, value);
    }

    /**
     * Gets the attribute value for TRIM_COST using the alias name TrimCost.
     * @return the TRIM_COST
     */
    public Number getTrimCost() {
        return (Number) getAttributeInternal(TRIMCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for TRIM_COST using the alias name TrimCost.
     * @param value value to set the TRIM_COST
     */
    public void setTrimCost(Number value) {
        setAttributeInternal(TRIMCOST, value);
    }

    /**
     * Gets the attribute value for WASH_COST using the alias name WashCost.
     * @return the WASH_COST
     */
    public Number getWashCost() {
        return (Number) getAttributeInternal(WASHCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for WASH_COST using the alias name WashCost.
     * @param value value to set the WASH_COST
     */
    public void setWashCost(Number value) {
        setAttributeInternal(WASHCOST, value);
    }

    /**
     * Gets the attribute value for CM_MERCHAND using the alias name CmMerchand.
     * @return the CM_MERCHAND
     */
    public Number getCmMerchand() {
        return (Number) getAttributeInternal(CMMERCHAND);
    }

    /**
     * Sets <code>value</code> as attribute value for CM_MERCHAND using the alias name CmMerchand.
     * @param value value to set the CM_MERCHAND
     */
    public void setCmMerchand(Number value) {
        setAttributeInternal(CMMERCHAND, value);
    }

    /**
     * Gets the attribute value for SMV using the alias name Smv.
     * @return the SMV
     */
    public Number getSmv() {
        return (Number) getAttributeInternal(SMV);
    }

    /**
     * Sets <code>value</code> as attribute value for SMV using the alias name Smv.
     * @param value value to set the SMV
     */
    public void setSmv(Number value) {
        setAttributeInternal(SMV, value);
    }

    /**
     * Gets the attribute value for FACTORY_AVG_EF using the alias name FactoryAvgEf.
     * @return the FACTORY_AVG_EF
     */
    public Number getFactoryAvgEf() {
        return (Number) getAttributeInternal(FACTORYAVGEF);
    }

    /**
     * Sets <code>value</code> as attribute value for FACTORY_AVG_EF using the alias name FactoryAvgEf.
     * @param value value to set the FACTORY_AVG_EF
     */
    public void setFactoryAvgEf(Number value) {
        setAttributeInternal(FACTORYAVGEF, value);
    }

    /**
     * Gets the attribute value for PROD_COST_LINE_PER_H using the alias name ProdCostLinePerH.
     * @return the PROD_COST_LINE_PER_H
     */
    public Number getProdCostLinePerH() {
        return (Number) getAttributeInternal(PRODCOSTLINEPERH);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_COST_LINE_PER_H using the alias name ProdCostLinePerH.
     * @param value value to set the PROD_COST_LINE_PER_H
     */
    public void setProdCostLinePerH(Number value) {
        setAttributeInternal(PRODCOSTLINEPERH, value);
    }

    /**
     * Gets the attribute value for CM_MANAGEMENT using the alias name CmManagement.
     * @return the CM_MANAGEMENT
     */
    public Number getCmManagement() {
        return (Number) getAttributeInternal(CMMANAGEMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for CM_MANAGEMENT using the alias name CmManagement.
     * @param value value to set the CM_MANAGEMENT
     */
    public void setCmManagement(Number value) {
        setAttributeInternal(CMMANAGEMENT, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for CREATED_BY using the alias name CreatedBy.
     * @return the CREATED_BY
     */
    public Number getCreatedBy() {
        return (Number) getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATED_BY using the alias name CreatedBy.
     * @param value value to set the CREATED_BY
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for CREATION_DATE using the alias name CreationDate.
     * @return the CREATION_DATE
     */
    public Date getCreationDate() {
        return (Date) getAttributeInternal(CREATIONDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for CREATION_DATE using the alias name CreationDate.
     * @param value value to set the CREATION_DATE
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @return the LAST_UPDATED_BY
     */
    public Number getLastUpdatedBy() {
        return (Number) getAttributeInternal(LASTUPDATEDBY);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_BY using the alias name LastUpdatedBy.
     * @param value value to set the LAST_UPDATED_BY
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**
     * Gets the attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @return the LAST_UPDATED_DATE
     */
    public Date getLastUpdatedDate() {
        return (Date) getAttributeInternal(LASTUPDATEDDATE);
    }

    /**
     * Sets <code>value</code> as attribute value for LAST_UPDATED_DATE using the alias name LastUpdatedDate.
     * @param value value to set the LAST_UPDATED_DATE
     */
    public void setLastUpdatedDate(Date value) {
        setAttributeInternal(LASTUPDATEDDATE, value);
    }

    /**
     * Gets the attribute value for FABRIC_DESC using the alias name FabricDesc.
     * @return the FABRIC_DESC
     */
    public String getFabricDesc() {
        return (String) getAttributeInternal(FABRICDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for FABRIC_DESC using the alias name FabricDesc.
     * @param value value to set the FABRIC_DESC
     */
    public void setFabricDesc(String value) {
        setAttributeInternal(FABRICDESC, value);
    }

    /**
     * Gets the attribute value for CM using the alias name Cm.
     * @return the CM
     */
    public Number getCm() {
        return (Number) getAttributeInternal(CM);
    }

    /**
     * Sets <code>value</code> as attribute value for CM using the alias name Cm.
     * @param value value to set the CM
     */
    public void setCm(Number value) {
        setAttributeInternal(CM, value);
    }

    /**
     * Gets the attribute value for OTHERS using the alias name Others.
     * @return the OTHERS
     */
    public Number getOthers() {
        return (Number) getAttributeInternal(OTHERS);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHERS using the alias name Others.
     * @param value value to set the OTHERS
     */
    public void setOthers(Number value) {
        setAttributeInternal(OTHERS, value);
    }

    /**
     * Gets the attribute value for SMS_QTY using the alias name SmsQty.
     * @return the SMS_QTY
     */
    public Number getSmsQty() {
        return (Number) getAttributeInternal(SMSQTY);
    }

    /**
     * Sets <code>value</code> as attribute value for SMS_QTY using the alias name SmsQty.
     * @param value value to set the SMS_QTY
     */
    public void setSmsQty(Number value) {
        setAttributeInternal(SMSQTY, value);
    }

    /**
     * Gets the attribute value for SAM using the alias name Sam.
     * @return the SAM
     */
    public Number getSam() {
        return (Number) getAttributeInternal(SAM);
    }

    /**
     * Sets <code>value</code> as attribute value for SAM using the alias name Sam.
     * @param value value to set the SAM
     */
    public void setSam(Number value) {
        setAttributeInternal(SAM, value);
    }

    /**
     * Gets the attribute value for COST_NEW using the alias name CostNew.
     * @return the COST_NEW
     */
    public Number getCostNew() {
        return (Number) getAttributeInternal(COSTNEW);
    }

    /**
     * Sets <code>value</code> as attribute value for COST_NEW using the alias name CostNew.
     * @param value value to set the COST_NEW
     */
    public void setCostNew(Number value) {
        setAttributeInternal(COSTNEW, value);
    }

    /**
     * Gets the attribute value for TOTAL_COST using the alias name TotalCost.
     * @return the TOTAL_COST
     */
    public Number getTotalCost() {
        return (Number) getAttributeInternal(TOTALCOST);
    }

    /**
     * Sets <code>value</code> as attribute value for TOTAL_COST using the alias name TotalCost.
     * @param value value to set the TOTAL_COST
     */
    public void setTotalCost(Number value) {
        setAttributeInternal(TOTALCOST, value);
    }

    /**
     * Gets the attribute value for STYLE_EFFICIENCY using the alias name StyleEfficiency.
     * @return the STYLE_EFFICIENCY
     */
    public Number getStyleEfficiency() {
        return (Number) getAttributeInternal(STYLEEFFICIENCY);
    }

    /**
     * Sets <code>value</code> as attribute value for STYLE_EFFICIENCY using the alias name StyleEfficiency.
     * @param value value to set the STYLE_EFFICIENCY
     */
    public void setStyleEfficiency(Number value) {
        setAttributeInternal(STYLEEFFICIENCY, value);
    }

    /**
     * Gets the attribute value for OTHER_CHARGE using the alias name OtherCharge.
     * @return the OTHER_CHARGE
     */
    public Number getOtherCharge() {
        return (Number) getAttributeInternal(OTHERCHARGE);
    }

    /**
     * Sets <code>value</code> as attribute value for OTHER_CHARGE using the alias name OtherCharge.
     * @param value value to set the OTHER_CHARGE
     */
    public void setOtherCharge(Number value) {
        setAttributeInternal(OTHERCHARGE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute ItemTotal.
     * @return the ItemTotal
     */
    public Number getItemTotal() {
        return (Number) getAttributeInternal(ITEMTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute ItemTotal.
     * @param value value to set the  ItemTotal
     */
    public void setItemTotal(Number value) {
        setAttributeInternal(ITEMTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute WetTotal.
     * @return the WetTotal
     */
    public Number getWetTotal() {
        return (Number) getAttributeInternal(WETTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute WetTotal.
     * @param value value to set the  WetTotal
     */
    public void setWetTotal(Number value) {
        setAttributeInternal(WETTOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute DryTotal.
     * @return the DryTotal
     */
    public Number getDryTotal() {
        return (Number) getAttributeInternal(DRYTOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute DryTotal.
     * @param value value to set the  DryTotal
     */
    public void setDryTotal(Number value) {
        setAttributeInternal(DRYTOTAL, value);
    }

    /**
     * Gets the attribute value for SHIPMENT using the alias name Shipment.
     * @return the SHIPMENT
     */
    public String getShipment() {
        return (String) getAttributeInternal(SHIPMENT);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT using the alias name Shipment.
     * @param value value to set the SHIPMENT
     */
    public void setShipment(String value) {
        setAttributeInternal(SHIPMENT, value);
    }

    /**
     * Gets the attribute value for SHIPMENT_VALUE using the alias name ShipmentValue.
     * @return the SHIPMENT_VALUE
     */
    public Number getShipmentValue() {
        return (Number) getAttributeInternal(SHIPMENTVALUE);
    }

    /**
     * Sets <code>value</code> as attribute value for SHIPMENT_VALUE using the alias name ShipmentValue.
     * @param value value to set the SHIPMENT_VALUE
     */
    public void setShipmentValue(Number value) {
        setAttributeInternal(SHIPMENTVALUE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute trims_total.
     * @return the trims_total
     */
    public String gettrims_total() {
        return (String) getAttributeInternal(TRIMS_TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute trims_total.
     * @param value value to set the  trims_total
     */
    public void settrims_total(String value) {
        setAttributeInternal(TRIMS_TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute others_total.
     * @return the others_total
     */
    public String getothers_total() {
        return (String) getAttributeInternal(OTHERS_TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute others_total.
     * @param value value to set the  others_total
     */
    public void setothers_total(String value) {
        setAttributeInternal(OTHERS_TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute fab_total.
     * @return the fab_total
     */
    public String getfab_total() {
        return (String) getAttributeInternal(FAB_TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute fab_total.
     * @param value value to set the  fab_total
     */
    public void setfab_total(String value) {
        setAttributeInternal(FAB_TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D2_TVO1_Total.
     * @return the D2_TVO1_Total
     */
    public String getD2_TVO1_Total() {
        return (String) getAttributeInternal(D2_TVO1_TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D2_TVO1_Total.
     * @param value value to set the  D2_TVO1_Total
     */
    public void setD2_TVO1_Total(String value) {
        setAttributeInternal(D2_TVO1_TOTAL, value);
    }

    /**
     * Gets the attribute value for the calculated attribute D2_TVO_total.
     * @return the D2_TVO_total
     */
    public String getD2_TVO_total() {
        return (String) getAttributeInternal(D2_TVO_TOTAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute D2_TVO_total.
     * @param value value to set the  D2_TVO_total
     */
    public void setD2_TVO_total(String value) {
        setAttributeInternal(D2_TVO_TOTAL, value);
    }

    /**
     * Gets the attribute value for PROD_PER_LINE_PER_H using the alias name ProdPerLinePerH.
     * @return the PROD_PER_LINE_PER_H
     */
    public Number getProdPerLinePerH() {
        return (Number) getAttributeInternal(PRODPERLINEPERH);
    }

    /**
     * Sets <code>value</code> as attribute value for PROD_PER_LINE_PER_H using the alias name ProdPerLinePerH.
     * @param value value to set the PROD_PER_LINE_PER_H
     */
    public void setProdPerLinePerH(Number value) {
        setAttributeInternal(PRODPERLINEPERH, value);
    }


    /**
     * Gets the associated <code>Row</code> using master-detail link XX_OM_POC_H_TVO.
     */
    public Row getXX_OM_POC_H_TVO() {
        return (Row)getAttributeInternal(XX_OM_POC_H_TVO);
    }

    /**
     * Sets the master-detail link XX_OM_POC_H_TVO between this object and <code>value</code>.
     */
    public void setXX_OM_POC_H_TVO(Row value) {
        setAttributeInternal(XX_OM_POC_H_TVO, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XX_OM_POC_D1_TVO.
     */
    public RowIterator getXX_OM_POC_D1_TVO() {
        return (RowIterator)getAttributeInternal(XX_OM_POC_D1_TVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XX_OM_POC_D2_TVO.
     */
    public RowIterator getXX_OM_POC_D2_TVO() {
        return (RowIterator)getAttributeInternal(XX_OM_POC_D2_TVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link XX_OM_POC_D2_TVO2.
     */
    public RowIterator getXX_OM_POC_D2_TVO2() {
        return (RowIterator)getAttributeInternal(XX_OM_POC_D2_TVO2);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link trimsVO.
     */
    public RowIterator gettrimsVO() {
        return (RowIterator)getAttributeInternal(TRIMSVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link others_VO.
     */
    public RowIterator getothers_VO() {
        return (RowIterator)getAttributeInternal(OTHERS_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link ASAM_AStyleEffiVO.
     */
    public RowIterator getASAM_AStyleEffiVO() {
        return (RowIterator)getAttributeInternal(ASAM_ASTYLEEFFIVO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link short_or_eccess_VO.
     */
    public RowIterator getshort_or_eccess_VO() {
        return (RowIterator)getAttributeInternal(SHORT_OR_ECCESS_VO);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link MDSIRsVO.
     */
    public RowIterator getMDSIRsVO() {
        return (RowIterator)getAttributeInternal(MDSIRSVO);
    }

    /**
     * Gets the view accessor <code>RowSet</code> colorLov1.
     */
    public RowSet getcolorLov1() {
        return (RowSet)getAttributeInternal(COLORLOV1);
    }

    /**
     * Gets the view accessor <code>RowSet</code> shorExcessVo1.
     */
    public RowSet getshorExcessVo1() {
        return (RowSet)getAttributeInternal(SHOREXCESSVO1);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
