package model.views;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 24 14:26:27 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XX_OM_POC_D2_TVO2Impl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XX_OM_POC_D2_TVO2Impl() {
    }
    
//    @Override
//    public void insertRow(Row row) {
//            row.setAttribute("ProcessId", 2);
//            super.insertRow(row);
//        }

}
