package model.views;

import java.sql.ResultSet;

import oracle.jbo.Row;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Nov 24 14:23:06 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class XX_OM_POC_D2_TVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public XX_OM_POC_D2_TVOImpl() {
    }
  
//   @Override
//   public void insertRow(Row row) {
//           row.setAttribute("ProcessId", 1);
//           super.insertRow(row);
//       }

}
