package model.services.client;

import model.services.common.AppModule;

import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 29 15:33:06 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleClient extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleClient() {
    }


    public void validateLines() {
        Object _ret = this.riInvokeExportedMethod(this,"validateLines",null,null);
        return;
    }

    public String copyRecords(String type, String PocId, String FobId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"copyRecords",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {type, PocId, FobId});
        return (String)_ret;
    }

    public void CopyItemsDetail() {
        Object _ret =
            this.riInvokeExportedMethod(this,"CopyItemsDetail",null,null);
        return;
    }

    public void CopyPrecost(String type) {
        Object _ret =
            this.riInvokeExportedMethod(this,"CopyPrecost",new String [] {"java.lang.String"},new Object[] {type});
        return;
    }

    public String createItems(String PocId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"createItems",new String [] {"java.lang.String"},new Object[] {PocId});
        return (String)_ret;
    }

    public void setSessionValues(String userId, String orgId, String respId,
                                 String respApplId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {userId, orgId, respId, respApplId});
        return;
    }

    public String getRespKey(String respId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getRespKey",new String [] {"java.lang.String"},new Object[] {respId});
        return (String)_ret;
    }

    public void Approve(String headerId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"Approve",new String [] {"java.lang.String"},new Object[] {headerId});
        return;
    }
}
