package model.services.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 29 15:33:06 BDT 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void validateLines();

    String copyRecords(String type, String headerId, String lineId);

    void CopyItemsDetail();


    void CopyPrecost(String type);

    String createItems(String PocId);

    void setSessionValues(String userId, String orgId, String respId,
                          String respApplId);

    String getRespKey(String respId);

    void Approve(String headerId);
}
